/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Kalyan' at '2/12/18 10:54 PM' with Gradle 3.0
 *
 * @author Kalyan, @date 2/12/18 10:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
