import java.io.File;

import org.gradle.tooling.GradleConnector;
import org.gradle.tooling.ProjectConnection;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Kalyan' at '2/11/18 6:13 PM' with Gradle 3.0
 *
 * @author Kalyan, @date 2/11/18 6:13 PM
 */
public class Library {
	Test t = new Test();
	
	public static void main(String[] args) {
		
		 first();
		 second();
	}

	private static void second() {
		
		ProjectConnection connection2 = GradleConnector.newConnector()
				    .forProjectDirectory(new File("../LicenseReport"))
				    .connect();
		
		 	String[] arg2 = "clean"
				 try {
				    connection2.newBuild().forTasks(arg2).run();
				 }
				 catch(Exception e){
					 e.printStackTrace();
				 } finally {
				    connection2.close();
				 }
	}

	private static void first() {
		ProjectConnection connection = GradleConnector.newConnector()
				    .forProjectDirectory(new File("."))
				    .connect();
		 	String[] arg = ""
				 try {
				    connection.newBuild().forTasks(arg).run();
				 }
				 catch(Exception e){
					 e.printStackTrace();
				 } finally {
				    connection.close();
				 }
	}
}
