import java.io.File;

import org.gradle.api.Project;
import org.gradle.tooling.GradleConnector;
import org.gradle.tooling.ProjectConnection;
import org.gradle.tooling.model.DomainObjectSet;
import org.gradle.tooling.model.GradleProject;
import org.gradle.tooling.model.GradleTask;
import org.gradle.tooling.model.gradle.GradleScript;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Kalyan' at '2/11/18 6:13 PM' with Gradle 3.0
 *
 * @author Kalyan, @date 2/11/18 6:13 PM
 */
public class Library {
	
	
	public static void main(String[] args) {
		 first();
		 second();
		 Test t = new Test();
		 t.mavenCentral().getUrl();
	}

	private static void second() {
				
		ProjectConnection connection2 = GradleConnector.newConnector()
				    .forProjectDirectory(new File("../LicenseReport"))
				    .connect();
		
		 	String[] arg2 = {"clean","dependencyLicenseReport"};
				 try {
				    connection2.newBuild().forTasks("").run();
				 }
				 catch(Exception e){
					 e.printStackTrace();
				 } finally {
				    connection2.close();
				 }
	}

	private static void first() {
		ProjectConnection connection = GradleConnector.newConnector()
				    .forProjectDirectory(new File("."))
				    .connect();
		 	String[] arg = {"clean","build","publishToMavenLocal"};
				 try {
				    connection.newBuild().forTasks(arg).run();
				 }
				 catch(Exception e){
					 e.printStackTrace();
				 } finally {
				    connection.close();
				 }
	}
}
